main: nl.lucasridder.survival.Main
name: Survival
version: 1.2
author: LucasRidder
api-version: 1.16

commands:
 gamemode:
  aliases: gm
  usage: "Usage: /<command> [survival|creative|adventure|spectator|0|1|2|3] ([player])"
 minigames:
  usage: "/<command>"
 lobby:
  aliases: hub
 kitpvp:
  usage: "/<command>"
 setspawn:
  usage: "/<command>"
 spawn:
  usage: "/<command>"
 stop:
  usage: "/<command>"
 staff:
  usage: "/<command>"
 vanish:
  aliases: v
  usage: "/<command>"
 set:
  usage: "/<command> [player] [string]"